# Use root/example as user/password credentials
version: '3.1'
#CMD tsc-watch --outDir ./build --onSuccess \
# "npm install pm2 -g ./build/server.js --name media -o ./logs/log.log -e ./logs/err.log --watch" --onFailure "echo failed to compile ts project"
services:
    clean-back:
        build:
            context: ../../
            dockerfile: ./src/docker/dev.Dockerfile
        container_name: clean-back
        command: npm run start:dev
        working_dir: /opt/web
        image: clean-back
        restart: always
        environment:
            host: mongo
            port: ${MONGO_CONTAINER_PORT}
            username: ${MONGO_USERNAME}
            password: ${MONGO_PASSWORD}
            dbName: ${MONGO_DB}
        volumes:
            - ../..:/opt/web
            - /otp/web/node_modules
            - ..:/opt/web/src

        ports:
            - ${HTTP_SERVER_LOCAL_PORT}:${HTTP_SERVER_CONTAINER_PORT}
            - ${WEBSOCKET_SERVER_LOCAL_PORT}:${WEBSOCKET_SERVER_CONTAINER_PORT}
            - ${GRPC_SERVER_LOCAL_PORT}:${GRPC_SERVER_CONTAINER_PORT}
        depends_on:
            - "mongo"
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        ports:
            - ${MONGO_LOCAL_PORT}:${MONGO_CONTAINER_PORT}

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
             ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
             ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
             ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_CONTAINER_PORT}/
        depends_on:
            - "mongo"