# Use root/example as user/password credentials
version: '3.1'

services:
    clean-back:
        build:
            context: ../../
            dockerfile: ./src/docker/Dockerfile
        container_name: clean-back
        command: npm run start:dev
        working_dir: /opt/web
        image: clean-back
        restart: always
        environment:
            host: mongo
            port: ${MONGO_CONTAINER_PORT}
            username: ${MONGO_USERNAME}
            password: ${MONGO_PASSWORD}
            dbName: ${MONGO_DB}
        ports:
            - ${SERVER_LOCAL_PORT}:${SERVER_CONTAINER_PORT}
        depends_on:
            - "mongo"
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        ports:
            - ${MONGO_LOCAL_PORT}:${MONGO_CONTAINER_PORT}

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
             ME_CONFIG_MONGODB_ADMINUSERNAME: root
             ME_CONFIG_MONGODB_ADMINPASSWORD: example
             ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:${MONGO_CONTAINER_PORT}/
        depends_on:
            - "mongo"